name = "Springfield"
host = "0.0.0.0"
port = 7788
players = 1024
#password = "verysecurepassword"
announce = false
#token = no-token
gamemode = "Freeroam"
website = "https://cenne.xyz"
language = "fr"
description = "A personnal free server"
debug = true
modules = [
  "js-module",
]
resources = ["core"]
tags = [ 
  "customTag1",
  "customTag2",
  "customTag3",
  "customTag4"
]
